	.align 2
gTilesetPalOverrides_General::
	.byte 5
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_General05

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2

	.align 2
gTilesetPalOverrides_Outside::
	.byte 5
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Outside05

	.byte 6
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Outside06

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2

	.align 2
gTilesetPalOverrides_Mariburg::
	.byte 7
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Mariburg07

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2

	.align 2
gTilesetPalOverrides_Costa::
	.byte 7
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Costa07

	.byte 8
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Costa08

	.byte 9
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Costa09

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2